// <auto-generated />
namespace Bobs_Tyres.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class subscriber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subscriber));
        
        string IMigrationMetadata.Id
        {
            get { return "201704111718530_subscriber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
